Write-Host "Installing Apps"
winget install "Oracle.JDK.20"
winget install "OpenJS.NodeJS"
winget install "Python.Python.3.8"

winget install "7zip.7zip"
winget install "Insecure.Nmap"

winget install "JetBrains.Toolbox"
winget install "Obsidian.Obsidian"
winget install "Mozilla.Firefox"
winget install "Spotify.Spotify"
winget install "Valve.Steam"
winget install "Oracle.VirtualBox"
winget install "ProtonTechnologies.ProtonVPN"
winget install "WiresharkFoundation.Wireshark"
winget install "VB-Audio.Voicemeeter.Banana"
winget install "Corsair.iCUE.5"
Write-Host "Installed Apps" 