theme = "ashen_bankai"

[editor]
line-number = "relative"
continue-comments = false
bufferline = "multiple"
end-of-line-diagnostics = "hint"
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name", "file-modification-indicator"]
right = ["diagnostics","position", "file-encoding", "file-type"]
separator = "|"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
diagnostics = ["warning", "error"]
workspace-diagnostics = ["warning", "error"]

[editor.lsp]
display-inlay-hints=true

[editor.inline-diagnostics]
cursor-line="warning"
